name: API Test

on:
  workflow_dispatch: # 手動実行トリガー
  push:
    # 自身のワークフロー定義ファイルが更新されたときだけトリガー
    paths:
      - .github/workflows/api-test.yaml

env:
  PR: 3

jobs:
  pr-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
      # Classic と v2 の両方を読むなら両方付ける
      repository-projects: read   # Classic Projects
      projects: read              # Projects v2

    steps:
      - uses: actions/checkout@v4
      - name: api-test
        # CLI で取得した PR 情報を Markdown にまとめる
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          OWNER="${{ github.repository_owner }}"
          REPO="${{ github.repository##*/}"       # or直接指定

          # 認証情報とスコープ確認
          gh auth status -t

          # gh auth refresh -s read:project

          # Classic / v2 判別
          gh pr view $PR --json projectCards,projectItems --jq '.'

          # GraphQL で直接問い合わせ
          gh api graphql -f owner=ORG -f repo=REPO -F number=$PR -f query='
            query($owner:String!,$repo:String!,$number:Int!){
              repository(owner:$owner,name:$repo){
                pullRequest(number:$number){
                  projectItems(first:10){ totalCount }
                }
              }
            }'

          # PR #123 の Project フィールドを jq で整形出力
          # gh pr view $PR --json projectItems \
          #   --jq '
          #     .projectItems[].fieldValues.nodes[]
          #     | {field: (.field.name // "-"), value: (.text // .name // .number // .date)}
          #   ' 
