name: pr check

on:
  workflow_dispatch: # 手動実行トリガー
  push:
    # 自身のワークフロー定義ファイルが更新されたときだけトリガー
    paths:
      - .github/workflows/pr-check.yaml
      - .github/workflows/script/collect_pr_status.sh

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pr-check
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ls -l .github/workflows/script/
          bash .github/workflows/script/collect_pr_status.sh
