name: pr check

on:
  workflow_dispatch: # 手動実行トリガー
  push:
    # 自身のワークフロー定義ファイルが更新されたときだけトリガー
    paths:
      - .github/workflows/pr-check.yaml
      - .github/workflows/script/collect_pr_status.py

jobs:
  pr-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - id: checkout-wiki
        # Wiki リポジトリをチェックアウト。存在しない場合でも失敗させない
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki
      - name: pr-check
        # CLI で取得した PR 情報を Markdown にまとめる
        env:
          GH_TOKEN: ${{ secrets.GH_PROJECT_PAT }}
          LOG_LEVEL: INFO
          LOGIN_USERS_B64: "eyJsb2dpblVzZXJzIjogW3sibG9naW5Vc2VyIjogImljaGktM2hFRyIsICJvcmdhbml6YXRpb24iOiAieW9ndXJ0In0sIHsibG9naW5Vc2VyIjogImljaGk3OTAxIiwgIm9yZ2FuaXphdGlvbiI6ICJjb3JpYW5kZXIifV19"
          SUB_REPOSITORY: owner/another-repo
        run: |
          ls -l .github/workflows/script/
          # メインおよびサブリポジトリの PR ステータスを収集
          for repo in "${GITHUB_REPOSITORY}" "$SUB_REPOSITORY"; do
            [ -z "$repo" ] && continue
            python .github/workflows/script/collect_pr_status.py wiki --repo "$repo"
          done
      - name: update-wiki
        # Wiki のチェックアウトが成功したときのみ更新を実行
        if: steps.checkout-wiki.outcome == 'success'
        env:
          LOG_LEVEL: INFO
        run: python .github/workflows/script/update_wiki.py wiki
